<a href="https://colab.research.google.com/github/Dhlih/Submission-Dicoding-Analisis-Sentimen/blob/main/Pelatihan_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Library

In [16]:
import pandas as pd  # Pandas untuk manipulasi dan analisis data
pd.options.mode.chained_assignment = None  # Menonaktifkan peringatan chaining

import numpy as np  # NumPy untuk komputasi numerik
import matplotlib.pyplot as plt  # Matplotlib untuk visualisasi data
import seaborn as sns  # Seaborn untuk visualisasi data statistik, mengatur gaya visualisasi
from sklearn.metrics import accuracy_score

import datetime as dt  # Manipulasi data waktu dan tanggal
import re  # Modul untuk bekerja dengan ekspresi reguler
import string  # Berisi konstanta string, seperti tanda baca

from nltk.tokenize import word_tokenize  # Tokenisasi teks
from nltk.corpus import stopwords  # Daftar kata-kata berhenti dalam teks

!pip install sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory  # Stemming (penghilangan imbuhan kata) dalam bahasa Indonesia
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory  # Menghapus kata-kata berhenti dalam bahasa Indonesia

from wordcloud import WordCloud  # Membuat visualisasi berbentuk awan kata (word cloud) dari teks

import nltk  # Import pustaka NLTK (Natural Language Toolkit).
nltk.download('punkt_tab')  # Mengunduh dataset yang diperlukan untuk tokenisasi teks.
nltk.download('stopwords')  # Mengunduh dataset yang berisi daftar kata-kata berhenti (stopwords) dalam berbagai bahasa.

Requirement already satisfied: sastrawi in /usr/local/lib/python3.12/dist-packages (1.0.1)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

## Loading Dataset

In [17]:
df = pd.read_csv("ulasan_ipusnas.csv")
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,82e83362-0763-4eab-9e3d-fc11930634a8,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"gabisa minjem, kesalahan pengiriman data mulu,...",1,124,2.1.0,2026-02-25 12:21:00,NaN,NaN,2.1.0
1,eb1e116f-41d2-4699-bee6-a86918bbd023,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"kadang bisa minjem buku kadang engga, awalnya ...",2,234,2.1.0,2026-02-01 08:49:07,NaN,NaN,2.1.0
2,c28895ee-210a-4be9-81a3-7ad9c1a8b191,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Ini kenapa setelah update data peminjaman, ant...",2,369,2.0.6,2026-01-26 15:43:13,NaN,NaN,2.0.6
3,d6273ac9-49fc-4d54-a80f-d01210795215,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Halo ipusnas! Kenapa dari bulan Januari sampai...,3,31,2.1.0,2026-02-23 06:17:42,NaN,NaN,2.1.0
4,682da2e3-3176-4589-87bb-956495cf64a7,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Aplikasi ini tujuannya memudahkan akses baca s...,1,185,2.1.0,2026-02-22 07:15:35,NaN,NaN,2.1.0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19959 entries, 0 to 19958
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              19959 non-null  object
 1   userName              19959 non-null  object
 2   userImage             19959 non-null  object
 3   content               19959 non-null  object
 4   score                 19959 non-null  int64
 5   thumbsUpCount         19959 non-null  int64
 6   reviewCreatedVersion  14981 non-null  object
 7   at                    19959 non-null  object
 8   replyContent          13130 non-null  object
 9   repliedAt             13130 non-null  object
 10  appVersion            14981 non-null  object
dtypes: int64(2), object(9)
memory usage: 1.7+ MB

In [19]:
df.isnull().sum()

reviewId                   0
userName                   0
userImage                  0
content                    0
score                      0
thumbsUpCount              0
reviewCreatedVersion    4978
at                         0
replyContent            6829
repliedAt               6829
appVersion              4978
dtype: int64

In [20]:
clean_df = df.dropna()
clean_df.isnull().sum()

reviewId                0
userName                0
userImage               0
content                 0
score                   0
thumbsUpCount           0
reviewCreatedVersion    0
at                      0
replyContent            0
repliedAt               0
appVersion              0
dtype: int64

In [21]:
clean_df.duplicated().sum()

np.int64(0)

## Preprocess Text

In [30]:
import re
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

def cleaningText(text):
    text = re.sub(r'@[A-Za-z0-9]+', '', text) # menghapus mention
    text = re.sub(r'#[A-Za-z0-9]+', '', text) # menghapus hashtag
    text = re.sub(r'RT[\s]', '', text) # menghapus RT
    text = re.sub(r"http\S+", '', text) # menghapus link
    text = re.sub(r'[0-9]+', '', text) # menghapus angka
    text = re.sub(r'[^\w\s]', '', text) # menghapus karakter selain huruf dan angka

    text = text.replace('\n', ' ') # mengganti baris baru dengan spasi
    text = text.translate(str.maketrans('', '', string.punctuation)) # menghapus semua tanda baca
    text = text.strip(' ') # menghapus karakter spasi dari kiri dan kanan teks
    return text

def casefoldingText(text): # Mengubah semua karakter dalam teks menjadi huruf kecil
    text = text.lower()
    return text

def tokenizingText(text): # Memecah atau membagi string, teks menjadi daftar token
    text = word_tokenize(text)
    return text

def toSentence(list_words): # Mengubah daftar kata menjadi kalimat
    sentence = ' '.join(word for word in list_words)
    return sentence

In [60]:
slang_words

{'@': 'di',
 'abis': 'habis',
 'ad': 'ada',
 'adlh': 'adalah',
 'afaik': 'as far as i know',
 'ahaha': 'haha',
 'aj': 'saja',
 'ajep-ajep': 'dunia gemerlap',
 'ak': 'saya',
 'akika': 'aku',
 'akkoh': 'aku',
 'akuwh': 'aku',
 'alay': 'norak',
 'alow': 'halo',
 'ambilin': 'ambilkan',
 'ancur': 'hancur',
 'anjrit': 'anjing',
 'anter': 'antar',
 'ap2': 'apa-apa',
 'apasih': 'apa sih',
 'apes': 'sial',
 'aps': 'apa',
 'aq': 'saya',
 'aquwh': 'aku',
 'asbun': 'asal bunyi',
 'aseekk': 'asyik',
 'asekk': 'asyik',
 'asem': 'asam',
 'aspal': 'asli tetapi palsu',
 'astul': 'asal tulis',
 'ato': 'atau',
 'au ah': 'tidak mau tahu',
 'awak': 'saya',
 'ay': 'sayang',
 'ayank': 'sayang',
 'b4': 'sebelum',
 'bakalan': 'akan',
 'bandes': 'bantuan desa',
 'bangedh': 'banget',
 'banpol': 'bantuan polisi',
 'banpur': 'bantuan tempur',
 'basbang': 'basi',
 'bcanda': 'bercanda',
 'bdg': 'bandung',
 'begajulan': 'nakal',
 'beliin': 'belikan',
 'bencong': 'banci',
 'bentar': 'sebentar',
 'ber3': 'bertiga',
 'beresin': 'membereskan',
 'bete': 'bosan',
 'beud': 'banget',
 'bg': 'abang',
 'bgmn': 'bagaimana',
 'bgt': 'banget',
 'bijimane': 'bagaimana',
 'bintal': 'bimbingan mental',
 'bkl': 'akan',
 'bknnya': 'bukannya',
 'blegug': 'bodoh',
 'blh': 'boleh',
 'bln': 'bulan',
 'blum': 'belum',
 'bnci': 'benci',
 'bnran': 'yang benar',
 'bodor': 'lucu',
 'bokap': 'ayah',
 'boker': 'buang air besar',
 'bokis': 'bohong',
 'boljug': 'boleh juga',
 'bonek': 'bocah nekat',
 'boyeh': 'boleh',
 'br': 'baru',
 'brg': 'bareng',
 'bro': 'saudara laki-laki',
 'bru': 'baru',
 'bs': 'bisa',
 'bsen': 'bosan',
 'bt': 'buat',
 'btw': 'ngomong-ngomong',
 'buaya': 'tidak setia',
 'bubbu': 'tidur',
 'bubu': 'tidur',
 'bumil': 'ibu hamil',
 'bw': 'bawa',
 'bwt': 'buat',
 'byk': 'banyak',
 'byrin': 'bayarkan',
 'cabal': 'sabar',
 'cadas': 'keren',
 'calo': 'makelar',
 'can': 'belum',
 'capcus': 'pergi',
 'caper': 'cari perhatian',
 'ce': 'cewek',
 'cekal': 'cegah tangkal',
 'cemen': 'penakut',
 'cengengesan': 'tertawa',
 'cepet': 'cepat',
 'cew': 'cewek',
 'chuyunk': 'sayang',
 'cimeng': 'ganja',
 'cipika cipiki': 'cium pipi kanan cium pipi kiri',
 'ciyh': 'sih',
 'ckepp': 'cakep',
 'ckp': 'cakep',
 'cmiiw': "correct me if i'm wrong",
 'cmpur': 'campur',
 'cong': 'banci',
 'conlok': 'cinta lokasi',
 'cowwyy': 'maaf',
 'cp': 'siapa',
 'cpe': 'capek',
 'cppe': 'capek',
 'cucok': 'cocok',
 'cuex': 'cuek',
 'cumi': 'Cuma miscall',
 'cups': 'culun',
 'curanmor': 'pencurian kendaraan bermotor',
 'curcol': 'curahan hati colongan',
 'cwek': 'cewek',
 'cyin': 'cinta',
 'd': 'di',
 'dah': 'deh',
 'dapet': 'dapat',
 'de': 'adik',
 'dek': 'adik',
 'demen': 'suka',
 'deyh': 'deh',
 'dgn': 'dengan',
 'diancurin': 'dihancurkan',
 'dimaafin': 'dimaafkan',
 'dimintak': 'diminta',
 'disono': 'di sana',
 'dket': 'dekat',
 'dkk': 'dan kawan-kawan',
 'dll': 'dan lain-lain',
 'dlu': 'dulu',
 'dngn': 'dengan',
 'dodol': 'bodoh',
 'doku': 'uang',
 'dongs': 'dong',
 'dpt': 'dapat',
 'dri': 'dari',
 'drmn': 'darimana',
 'drtd': 'dari tadi',
 'dst': 'dan seterusnya',
 'dtg': 'datang',
 'duh': 'aduh',
 'duren': 'durian',
 'ed': 'edisi',
 'egp': 'emang gue pikirin',
 'eke': 'aku',
 'elu': 'kamu',
 'emangnya': 'memangnya',
 'emng': 'memang',
 'endak': 'tidak',
 'enggak': 'tidak',
 'envy': 'iri',
 'ex': 'mantan',
 'fax': 'facsimile',
 'fifo': 'first in first out',
 'folbek': 'follow back',
 'fyi': 'sebagai informasi',
 'gaada': 'tidak ada uang',
 'gag': 'tidak',
 'gaje': 'tidak jelas',
 'gak papa': 'tidak apa-apa',
 'gan': 'juragan',
 'gaptek': 'gagap teknologi',
 'gatek': 'gagap teknologi',
 'gawe': 'kerja',
 'gbs': 'tidak bisa',
 'gebetan': 'orang yang disuka',
 'geje': 'tidak jelas',
 'gepeng': 'gelandangan dan pengemis',
 'ghiy': 'lagi',
 'gile': 'gila',
 'gimana': 'bagaimana',
 'gino': 'gigi nongol',
 'githu': 'gitu',
 'gj': 'tidak jelas',
 'gmana': 'bagaimana',
 'gn': 'begini',
 'goblok': 'bodoh',
 'golput': 'golongan putih',
 'gowes': 'mengayuh sepeda',
 'gpny': 'tidak punya',
 'gr': 'gede rasa',
 'gretongan': 'gratisan',
 'gtau': 'tidak tahu',
 'gua': 'saya',
 'guoblok': 'goblok',
 'gw': 'saya',
 'ha': 'tertawa',
 'haha': 'tertawa',
 'hallow': 'halo',
 'hankam': 'pertahanan dan keamanan',
 'hehe': 'he',
 'helo': 'halo',
 'hey': 'hai',
 'hlm': 'halaman',
 'hny': 'hanya',
 'hoax': 'isu bohong',
 'hr': 'hari',
 'hrus': 'harus',
 'hubdar': 'perhubungan darat',
 'huff': 'mengeluh',
 'hum': 'rumah',
 'humz': 'rumah',
 'ilang': 'hilang',
 'ilfil': 'tidak suka',
 'imho': 'in my humble opinion',
 'imoetz': 'imut',
 'item': 'hitam',
 'itungan': 'hitungan',
 'iye': 'iya',
 'ja': 'saja',
 'jadiin': 'jadi',
 'jaim': 'jaga image',
 'jayus': 'tidak lucu',
 'jdi': 'jadi',
 'jem': 'jam',
 'jga': 'juga',
 'jgnkan': 'jangankan',
 'jir': 'anjing',
 'jln': 'jalan',
 'jomblo': 'tidak punya pacar',
 'jubir': 'juru bicara',
 'jutek': 'galak',
 'k': 'ke',
 'kab': 'kabupaten',
 'kabor': 'kabur',
 'kacrut': 'kacau',
 'kadiv': 'kepala divisi',
 'kagak': 'tidak',
 'kalo': 'kalau',
 'kampret': 'sialan',
 'kamtibmas': 'keamanan dan ketertiban masyarakat',
 'kamuwh': 'kamu',
 'kanwil': 'kantor wilayah',
 'karna': 'karena',
 'kasubbag': 'kepala subbagian',
 'katrok': 'kampungan',
 'kayanya': 'kayaknya',
 'kbr': 'kabar',
 'kdu': 'harus',
 'kec': 'kecamatan',
 'kejurnas': 'kejuaraan nasional',
 'kekeuh': 'keras kepala',
 'kel': 'kelurahan',
 'kemaren': 'kemarin',
 'kepengen': 'mau',
 'kepingin': 'mau',
 'kepsek': 'kepala sekolah',
 'kesbang': 'kesatuan bangsa',
 'kesra': 'kesejahteraan rakyat',
 'ketrima': 'diterima',
 'kgiatan': 'kegiatan',
 'kibul': 'bohong',
 'kimpoi': 'kawin',
 'kl': 'kalau',
 'klianz': 'kalian',
 'kloter': 'kelompok terbang',
 'klw': 'kalau',
 'km': 'kamu',
 'kmps': 'kampus',
 'kmrn': 'kemarin',
 'knal': 'kenal',
 'knp': 'kenapa',
 'kodya': 'kota madya',
 'komdis': 'komisi disiplin',
 'komsov': 'komunis sovyet',
 'kongkow': 'kumpul bareng teman-teman',
 'kopdar': 'kopi darat',
 'korup': 'korupsi',
 'kpn': 'kapan',
 'krenz': 'keren',
 'krm': 'kirim',
 'kt': 'kita',
 'ktmu': 'ketemu',
 'ktr': 'kantor',
 'kuper': 'kurang pergaulan',
 'kw': 'imitasi',
 'kyk': 'seperti',
 'la': 'lah',
 'lam': 'salam',
 'lamp': 'lampiran',
 'lanud': 'landasan udara',
 'latgab': 'latihan gabungan',
 'lebay': 'berlebihan',
 'leh': 'boleh',
 'lelet': 'lambat',
 'lemot': 'lambat',
 'lgi': 'lagi',
 'lgsg': 'langsung',
 'liat': 'lihat',
 'litbang': 'penelitian dan pengembangan',
 'lmyn': 'lumayan',
 'lo': 'kamu',
 'loe': 'kamu',
 'lola': 'lambat berfikir',
 'louph': 'cinta',
 'low': 'kalau',
 'lp': 'lupa',
 'luber': 'langsung, umum, bebas, dan rahasia',
 'luchuw': 'lucu',
 'lum': 'belum',
 'luthu': 'lucu',
 'lwn': 'lawan',
 'maacih': 'terima kasih',
 'mabal': 'bolos',
 'macem': 'macam',
 'macih': 'masih',
 'maem': 'makan',
 'magabut': 'makan gaji buta',
 'maho': 'homo',
 'mak jang': 'kaget',
 'maksain': 'memaksa',
 'malem': 'malam',
 'mam': 'makan',
 'maneh': 'kamu',
 'maniez': 'manis',
 'mao': 'mau',
 'masukin': 'masukkan',
 'melu': 'ikut',
 'mepet': 'dekat sekali',
 'mgu': 'minggu',
 'migas': 'minyak dan gas bumi',
 'mikol': 'minuman beralkohol',
 'miras': 'minuman keras',
 'mlah': 'malah',
 'mngkn': 'mungkin',
 'mo': 'mau',
 'mokad': 'mati',
 'moso': 'masa',
 'mpe': 'sampai',
 'msk': 'masuk',
 'mslh': 'masalah',
 'mt': 'makan teman',
 'mubes': 'musyawarah besar',
 'mulu': 'melulu',
 'mumpung': 'selagi',
 'munas': 'musyawarah nasional',
 'muntaber': 'muntah dan berak',
 'musti': 'mesti',
 'muupz': 'maaf',
 'mw': 'now watching',
 'n': 'dan',
 'nanam': 'menanam',
 'nanya': 'bertanya',
 'napa': 'kenapa',
 'napi': 'narapidana',
 'napza': 'narkotika, alkohol, psikotropika, dan zat adiktif ',
 'narkoba': 'narkotika, psikotropika, dan obat terlarang',
 'nasgor': 'nasi goreng',
 'nda': 'tidak',
 'ndiri': 'sendiri',
 'ne': 'ini',
 'nekolin': 'neokolonialisme',
 'nembak': 'menyatakan cinta',
 'ngabuburit': 'menunggu berbuka puasa',
 'ngaku': 'mengaku',
 'ngambil': 'mengambil',
 'nganggur': 'tidak punya pekerjaan',
 'ngapah': 'kenapa',
 'ngaret': 'terlambat',
 'ngasih': 'memberikan',
 'ngebandel': 'berbuat bandel',
 'ngegosip': 'bergosip',
 'ngeklaim': 'mengklaim',
 'ngeksis': 'menjadi eksis',
 'ngeles': 'berkilah',
 'ngelidur': 'menggigau',
 'ngerampok': 'merampok',
 'ngga': 'tidak',
 'ngibul': 'berbohong',
 'ngiler': 'mau',
 'ngiri': 'iri',
 'ngisiin': 'mengisikan',
 'ngmng': 'bicara',
 'ngomong': 'bicara',
 'ngubek2': 'mencari-cari',
 'ngurus': 'mengurus',
 'nie': 'ini',
 'nih': 'ini',
 'niyh': 'nih',
 'nmr': 'nomor',
 'nntn': 'nonton',
 'nobar': 'nonton bareng',
 'np': 'now playing',
 'ntar': 'nanti',
 'ntn': 'nonton',
 'numpuk': 'bertumpuk',
 'nutupin': 'menutupi',
 'nyari': 'mencari',
 'nyekar': 'menyekar',
 'nyicil': 'mencicil',
 'nyoblos': 'mencoblos',
 'nyokap': 'ibu',
 'ogah': 'tidak mau',
 'ol': 'online',
 'ongkir': 'ongkos kirim',
 'oot': 'out of topic',
 'org2': 'orang-orang',
 'ortu': 'orang tua',
 'otda': 'otonomi daerah',
 'otw': 'on the way, sedang di jalan',
 'pacal': 'pacar',
 'pake': 'pakai',
 'pala': 'kepala',
 'pansus': 'panitia khusus',
 'parpol': 'partai politik',
 'pasutri': 'pasangan suami istri',
 'pd': 'pada',
 'pede': 'percaya diri',
 'pelatnas': 'pemusatan latihan nasional',
 'pemda': 'pemerintah daerah',
 'pemkot': 'pemerintah kota',
 'pemred': 'pemimpin redaksi',
 'penjas': 'pendidikan jasmani',
 'perda': 'peraturan daerah',
 'perhatiin': 'perhatikan',
 'pesenan': 'pesanan',
 'pgang': 'pegang',
 'pi': 'tapi',
 'pilkada': 'pemilihan kepala daerah',
 'pisan': 'sangat',
 'pk': 'penjahat kelamin',
 'plg': 'paling',
 'pmrnth': 'pemerintah',
 'polantas': 'polisi lalu lintas',
 'ponpes': 'pondok pesantren',
 'pp': 'pulang pergi',
 'prg': 'pergi',
 'prnh': 'pernah',
 'psen': 'pesan',
 'pst': 'pasti',
 'pswt': 'pesawat',
 'pw': 'posisi nyaman',
 'qmu': 'kamu',
 'rakor': 'rapat koordinasi',
 'ranmor': 'kendaraan bermotor',
 're': 'reply',
 'ref': 'referensi',
 'rehab': 'rehabilitasi',
 'rempong': 'sulit',
 'repp': 'balas',
 'restik': 'reserse narkotika',
 'rhs': 'rahasia',
 'rmh': 'rumah',
 'ru': 'baru',
 'ruko': 'rumah toko',
 'rusunawa': 'rumah susun sewa',
 'ruz': 'terus',
 'saia': 'saya',
 'salting': 'salah tingkah',
 'sampe': 'sampai',
 'samsek': 'sama sekali',
 'sapose': 'siapa',
 'satpam': 'satuan pengamanan',
 'sbb': 'sebagai berikut',
 'sbh': 'sebuah',
 'sbnrny': 'sebenarnya',
 'scr': 'secara',
 'sdgkn': 'sedangkan',
 'sdkt': 'sedikit',
 'se7': 'setuju',
 'sebelas dua belas': 'mirip',
 'sembako': 'sembilan bahan pokok',
 'sempet': 'sempat',
 'sendratari': 'seni drama tari',
 'sgt': 'sangat',
 'shg': 'sehingga',
 'siech': 'sih',
 'sikon': 'situasi dan kondisi',
 'sinetron': 'sinema elektronik',
 'siramin': 'siramkan',
 'sj': 'saja',
 'skalian': 'sekalian',
 'sklh': 'sekolah',
 'skt': 'sakit',
 'slesai': 'selesai',
 'sll': 'selalu',
 'slma': 'selama',
 'slsai': 'selesai',
 'smpt': 'sempat',
 'smw': 'semua',
 'sndiri': 'sendiri',
 'soljum': 'sholat jumat',
 'songong': 'sombong',
 'sory': 'maaf',
 'sosek': 'sosial-ekonomi',
 'sotoy': 'sok tahu',
 'spa': 'siapa',
 'sppa': 'siapa',
 'spt': 'seperti',
 'srtfkt': 'sertifikat',
 'stiap': 'setiap',
 'stlh': 'setelah',
 'suk': 'masuk',
 'sumpek': 'sempit',
 'syg': 'sayang',
 't4': 'tempat',
 'tajir': 'kaya',
 'tau': 'tahu',
 'taw': 'tahu',
 'td': 'tadi',
 'tdk': 'tidak',
 'teh': 'kakak perempuan',
 'telat': 'terlambat',
 'telmi': 'telat berpikir',
 'temen': 'teman',
 'tengil': 'menyebalkan',
 'tepar': 'terkapar',
 'tggu': 'tunggu',
 'tgu': 'tunggu',
 'thankz': 'terima kasih',
 'thn': 'tahun',
 'tilang': 'bukti pelanggaran',
 'tipiwan': 'TvOne',
 'tks': 'terima kasih',
 'tlp': 'telepon',
 'tls': 'tulis',
 'tmbah': 'tambah',
 'tmen2': 'teman-teman',
 'tmpah': 'tumpah',
 'tmpt': 'tempat',
 'tngu': 'tunggu',
 'tnyta': 'ternyata',
 'tokai': 'tai',
 'toserba': 'toko serba ada',
 'tpi': 'tapi',
 'trdhulu': 'terdahulu',
 'trima': 'terima kasih',
 'trm': 'terima',
 'trs': 'terus',
 'trutama': 'terutama',
 'ts': 'penulis',
 'tst': 'tahu sama tahu',
 'ttg': 'tentang',
 'tuch': 'tuh',
 'tuir': 'tua',
 'tw': 'tahu',
 'u': 'kamu',
 'ud': 'sudah',
 'udah': 'sudah',
 'ujg': 'ujung',
 'ul': 'ulangan',
 'unyu': 'lucu',
 'uplot': 'unggah',
 'urang': 'saya',
 'usah': 'perlu',
 'utk': 'untuk',
 'valas': 'valuta asing',
 'w/': 'dengan',
 'wadir': 'wakil direktur',
 'wamil': 'wajib militer',
 'warkop': 'warung kopi',
 'warteg': 'warung tegal',
 'wat': 'buat',
 'wkt': 'waktu',
 'wtf': 'what the fuck',
 'xixixi': 'tertawa',
 'ya': 'iya',
 'yap': 'iya',
 'yaudah': 'ya sudah',
 'yawdah': 'ya sudah',
 'yg': 'yang',
 'yl': 'yang lain',
 'yo': 'iya',
 'yowes': 'ya sudah',
 'yup': 'iya',
 '7an': 'tujuan',
 'ababil': 'abg labil',
 'acc': 'accord',
 'adlah': 'adalah',
 'adoh': 'aduh',
 'aha': 'tertawa',
 'aing': 'saya',
 'aja': 'saja',
 'ajj': 'saja',
 'aka': 'dikenal juga sebagai',
 'akko': 'aku',
 'akku': 'aku',
 'akyu': 'aku',
 'aljasa': 'asal jadi saja',
 'ama': 'sama',
 'ambl': 'ambil',
 'anjir': 'anjing',
 'ank': 'anak',
 'ap': 'apa',
 'apaan': 'apa',
 'ape': 'apa',
 'aplot': 'unggah',
 'apva': 'apa',
 'aqu': 'aku',
 'asap': 'sesegera mungkin',
 'aseek': 'asyik',
 'asek': 'asyik',
 'aseknya': 'asyiknya',
 'asoy': 'asyik',
 'astrojim': 'astagfirullahaladzim',
 'ath': 'kalau begitu',
 'atuh': 'kalau begitu',
 'ava': 'avatar',
 'aws': 'awas',
 'ayang': 'sayang',
 'ayok': 'ayo',
 'bacot': 'banyak bicara',
 'bales': 'balas',
 'bangdes': 'pembangunan desa',
 'bangkotan': 'tua',
 'banpres': 'bantuan presiden',
 'bansarkas': 'bantuan sarana kesehatan',
 'bazis': 'badan amal, zakat, infak, dan sedekah',
 'bcoz': 'karena',
 'beb': 'sayang',
 'bejibun': 'banyak',
 'belom': 'belum',
 'bener': 'benar',
 'ber2': 'berdua',
 'berdikari': 'berdiri di atas kaki sendiri',
 'bet': 'banget',
 'beti': 'beda tipis',
 'beut': 'banget',
 'bgd': 'banget',
 'bgs': 'bagus',
 'bhubu': 'tidur',
 'bimbuluh': 'bimbingan dan penyuluhan',
 'bisi': 'kalau-kalau',
 'bkn': 'bukan',
 'bl': 'beli',
 'blg': 'bilang',
 'blm': 'belum',
 'bls': 'balas',
 'bnchi': 'benci',
 'bngung': 'bingung',
 'bnyk': 'banyak',
 'bohay': 'badan aduhai',
 'bokep': 'porno',
 'bokin': 'pacar',
 'bole': 'boleh',
 'bolot': 'bodoh',
 'bonyok': 'ayah ibu',
 'bpk': 'bapak',
 'brb': 'segera kembali',
 'brngkt': 'berangkat',
 'brp': 'berapa',
 'brur': 'saudara laki-laki',
 'bsa': 'bisa',
 'bsk': 'besok',
 'bu_bu': 'tidur',
 'bubarin': 'bubarkan',
 'buber': 'buka bersama',
 'bujubune': 'luar biasa',
 'buser': 'buru sergap',
 'bwhn': 'bawahan',
 'byar': 'bayar',
 'byr': 'bayar',
 'c8': 'chat',
 'cabut': 'pergi',
 'caem': 'cakep',
 'cama-cama': 'sama-sama',
 'cangcut': 'celana dalam',
 'cape': 'capek',
 'caur': 'jelek',
 'cekak': 'tidak ada uang',
 'cekidot': 'coba lihat',
 'cemplungin': 'cemplungkan',
 'ceper': 'pendek',
 'ceu': 'kakak perempuan',
 'cewe': 'cewek',
 'cibuk': 'sibuk',
 'cin': 'cinta',
 'ciye': 'cie',
 'ckck': 'ck',
 'clbk': 'cinta lama bersemi kembali',
 'cmpr': 'campur',
 'cnenk': 'senang',
 'congor': 'mulut',
 'cow': 'cowok',
 'coz': 'karena',
 'cpa': 'siapa',
 'gokil': 'gila',
 'gombal': 'suka merayu',
 'gpl': 'tidak pakai lama',
 'gpp': 'tidak apa-apa',
 'gretong': 'gratis',
 'gt': 'begitu',
 'gtw': 'tidak tahu',
 'gue': 'saya',
 'guys': 'teman-teman',
 'gws': 'cepat sembuh',
 'haghaghag': 'tertawa',
 'hakhak': 'tertawa',
 'handak': 'bahan peledak',
 'hansip': 'pertahanan sipil',
 'hellow': 'halo',
 'helow': 'halo',
 'hi': 'hai',
 'hlng': 'hilang',
 'hnya': 'hanya',
 'houm': 'rumah',
 'hrs': 'harus',
 'hubad': 'hubungan angkatan darat',
 'hubla': 'perhubungan laut',
 'huft': 'mengeluh',
 'humas': 'hubungan masyarakat',
 'idk': 'saya tidak tahu',
 'ilfeel': 'tidak suka',
 'imba': 'jago sekali',
 'imoet': 'imut',
 'info': 'informasi',
 'itung': 'hitung',
 'isengin': 'bercanda',
 'iyala': 'iya lah',
 'iyo': 'iya',
 'jablay': 'jarang dibelai',
 'jadul': 'jaman dulu',
 'jancuk': 'anjing',
 'jd': 'jadi',
 'jdikan': 'jadikan',
 'jg': 'juga',
 'jgn': 'jangan',
 'jijay': 'jijik',
 'jkt': 'jakarta',
 'jnj': 'janji',
 'jth': 'jatuh',
 'jurdil': 'jujur adil',
 'jwb': 'jawab',
 'ka': 'kakak',
 'kabag': 'kepala bagian',
 'kacian': 'kasihan',
 'kadit': 'kepala direktorat',
 'kaga': 'tidak',
 'kaka': 'kakak',
 'kamtib': 'keamanan dan ketertiban',
 'kamuh': 'kamu',
 'kamyu': 'kamu',
 'kapt': 'kapten',
 'kasat': 'kepala satuan',
 'kasubbid': 'kepala subbidang',
 'kau': 'kamu',
 'kbar': 'kabar',
 'kcian': 'kasihan',
 'keburu': 'terlanjur',
 'kedubes': 'kedutaan besar',
 'kek': 'seperti',
 'keknya': 'kayaknya',
 'keliatan': 'kelihatan',
 'keneh': 'masih',
 'kepikiran': 'terpikirkan',
 'kepo': 'mau tahu urusan orang',
 'kere': 'tidak punya uang',
 'kesian': 'kasihan',
 'ketauan': 'ketahuan',
 'keukeuh': 'keras kepala',
 'khan': 'kan',
 'kibus': 'kaki busuk',
 'kk': 'kakak',
 'klian': 'kalian',
 'klo': 'kalau',
 'kluarga': 'keluarga',
 'klwrga': 'keluarga',
 'kmari': 'kemari',
 'kmpus': 'kampus',
 'kn': 'kan',
 'knl': 'kenal',
 'knpa': 'kenapa',
 'kog': 'kok',
 'kompi': 'komputer',
 'komtiong': 'komunis Tiongkok',
 'konjen': 'konsulat jenderal',
 'koq': 'kok',
 'kpd': 'kepada',
 'kptsan': 'keputusan',
 'krik': 'garing',
 'krn': 'karena',
 'ktauan': 'ketahuan',
 'ktny': 'katanya',
 'kudu': 'harus',
 'kuq': 'kok',
 'ky': 'seperti',
 'kykny': 'kayanya',
 'laka': 'kecelakaan',
 'lambreta': 'lambat',
 'lansia': 'lanjut usia',
 'lapas': 'lembaga pemasyarakatan',
 'lbur': 'libur',
 'lekong': 'laki-laki',
 'lg': 'lagi',
 'lgkp': 'lengkap',
 'lht': 'lihat',
 'linmas': 'perlindungan masyarakat',
 'lmyan': 'lumayan',
 'lngkp': 'lengkap',
 'loch': 'loh',
 'lol': 'tertawa',
 'lom': 'belum',
 'loupz': 'cinta',
 'lowh': 'kamu',
 'lu': 'kamu',
 'luchu': 'lucu',
 'luff': 'cinta',
 'luph': 'cinta',
 'lw': 'kamu',
 'lwt': 'lewat',
 'maaciw': 'terima kasih',
 'mabes': 'markas besar',
 'macem-macem': 'macam-macam',
 'madesu': 'masa depan suram',
 'maen': 'main',
 'mahatma': 'maju sehat bersama',
 'mak': 'ibu',
 'makasih': 'terima kasih',
 'malah': 'bahkan',
 'malu2in': 'memalukan',
 'mamz': 'makan',
 'manies': 'manis',
 'mantep': 'mantap',
 'markus': 'makelar kasus',
 'mba': 'mbak',
 'mending': 'lebih baik',
 'mgkn': 'mungkin',
 'mhn': 'mohon',
 'miker': 'minuman keras',
 'milis': 'mailing list',
 'mksd': 'maksud',
 'mls': 'malas',
 'mnt': 'minta',
 'moge': 'motor gede',
 'mokat': 'mati',
 'mosok': 'masa',
 'msh': 'masih',
 'mskpn': 'meskipun',
 'msng2': 'masing-masing',
 'muahal': 'mahal',
 'muker': 'musyawarah kerja',
 'mumet': 'pusing',
 'muna': 'munafik',
 'munaslub': 'musyawarah nasional luar biasa',
 'musda': 'musyawarah daerah',
 'muup': 'maaf',
 'muuv': 'maaf',
 'nal': 'kenal',
 'nangis': 'menangis',
 'naon': 'apa',
 'napol': 'narapidana politik',
 'naq': 'anak',
 'narsis': 'bangga pada diri sendiri',
 'nax': 'anak',
 'ndak': 'tidak',
 'ndut': 'gendut',
 'nekolim': 'neokolonialisme',
 'nelfon': 'menelepon',
 'ngabis2in': 'menghabiskan',
 'ngakak': 'tertawa',
 'ngambek': 'marah',
 'ngampus': 'pergi ke kampus',
 'ngantri': 'mengantri',
 'ngapain': 'sedang apa',
 'ngaruh': 'berpengaruh',
 'ngawur': 'berbicara sembarangan',
 'ngeceng': 'kumpul bareng-bareng',
 'ngeh': 'sadar',
 'ngekos': 'tinggal di kos',
 'ngelamar': 'melamar',
 'ngeliat': 'melihat',
 'ngemeng': 'bicara terus-terusan',
 'ngerti': 'mengerti',
 'nggak': 'tidak',
 'ngikut': 'ikut',
 'nginep': 'menginap',
 'ngisi': 'mengisi',
 'ngmg': 'bicara',
 'ngocol': 'lucu',
 'ngomongin': 'membicarakan',
 'ngumpul': 'berkumpul',
 'ni': 'ini',
 'nyasar': 'tersesat',
 'nyariin': 'mencari',
 'nyiapin': 'mempersiapkan',
 'nyiram': 'menyiram',
 'nyok': 'ayo',
 'o/': 'oleh',
 'ok': 'ok',
 'priksa': 'periksa',
 'pro': 'profesional',
 'psn': 'pesan',
 'psti': 'pasti',
 'puanas': 'panas',
 'qmo': 'kamu',
 'qt': 'kita',
 'rame': 'ramai',
 'raskin': 'rakyat miskin',
 'red': 'redaksi',
 'reg': 'register',
 'rejeki': 'rezeki',
 'renstra': 'rencana strategis',
 'reskrim': 'reserse kriminal',
 'sni': 'sini',
 'somse': 'sombong sekali',
 'sorry': 'maaf',
 'sosbud': 'sosial-budaya',
 'sospol': 'sosial-politik',
 'sowry': 'maaf',
 'spd': 'sepeda',
 'sprti': 'seperti',
 'spy': 'supaya',
 'stelah': 'setelah',
 'subbag': 'subbagian',

In [78]:
import json

with open('slang_words.json', 'r') as f:
    slang_words = json.load(f)

def fix_slangwords(text):
    words = text.split()
    print(words)
    fixed_words = []

    for word in words:
        if word.lower() in slang_words:
            fixed_words.append(slang_words[word.lower()])
        else:
            fixed_words.append(word)

    fixed_text = ' '.join(fixed_words)
    return fixed_text

with open('stop_words.txt', 'r') as f:
    stop_words = set(f.read().splitlines())

def filteringText(text): # Menghapus stopwords dalam teks
    filtered = []
    for txt in text:
        if txt not in stop_words:
            filtered.append(txt)
    text = filtered
    return text

In [31]:
# Membersihkan teks dan menyimpannya di kolom 'text_clean'
clean_df['text_clean'] = clean_df['content'].apply(cleaningText)

# Mengubah huruf dalam teks menjadi huruf kecil dan menyimpannya di 'text_casefoldingText'
clean_df['text_casefoldingText'] = clean_df['text_clean'].apply(casefoldingText)

# Mengganti kata-kata slang dengan kata-kata standar dan menyimpannya di 'text_slangwords'
clean_df['text_slangwords'] = clean_df['text_casefoldingText'].apply(fix_slangwords)

# Memecah teks menjadi token (kata-kata) dan menyimpannya di 'text_tokenizingText'
clean_df['text_tokenizingText'] = clean_df['text_slangwords'].apply(tokenizingText)

# Menghapus kata-kata stop (kata-kata umum) dan menyimpannya di 'text_stopword'
clean_df['text_stopword'] = clean_df['text_tokenizingText'].apply(filteringText)

# Menggabungkan token-token menjadi kalimat dan menyimpannya di 'text_akhir'
clean_df['text_akhir'] = clean_df['text_stopword'].apply(toSentence)

In [33]:
clean_df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,text_clean,text_casefoldingText,text_slangwords,text_tokenizingText,text_stopword,text_akhir
23,d5f0a704-9260-47f4-960d-153ab64d6cf4,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"Setelah diupdate krn keperluan tugas, rupanya ...",1,46,2.0.6,2026-01-29 01:38:27,Hallo Liliy! Terima kasih sudah memberikan ula...,2022-03-27 08:52:58,2.0.6,Setelah diupdate krn keperluan tugas rupanya g...,setelah diupdate krn keperluan tugas rupanya g...,setelah diupdate krn keperluan tugas rupanya g...,"[setelah, diupdate, krn, keperluan, tugas, rup...","[setelah, diupdate, krn, keperluan, tugas, rup...",setelah diupdate krn keperluan tugas rupanya g...
28,27609d0c-739b-4a34-847b-ff4a6a8c3fdc,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Saya Download Aplikasi Ipusnas Langsung di Pla...,1,12,2.0.6,2026-01-25 02:42:18,Hallo Usman! Kami mohon maaf atas kendala dan ...,2023-04-01 11:01:42,2.0.6,Saya Download Aplikasi Ipusnas Langsung di Pla...,saya download aplikasi ipusnas langsung di pla...,saya download aplikasi ipusnas langsung di pla...,"[saya, download, aplikasi, ipusnas, langsung, ...","[saya, download, aplikasi, ipusnas, langsung, ...",saya download aplikasi ipusnas langsung di pla...
33,96709d16-28e3-4dc9-aef2-7562a85b129e,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Terima kasih sudah memberi kesempatan untuk ya...,2,3,2.0.6,2026-01-24 23:28:33,Hallo Puristi! Kami mohon maaf atas ketidaknya...,2024-09-09 01:34:17,2.0.6,Terima kasih sudah memberi kesempatan untuk ya...,terima kasih sudah memberi kesempatan untuk ya...,terima kasih sudah memberi kesempatan untuk ya...,"[terima, kasih, sudah, memberi, kesempatan, un...","[terima, kasih, sudah, memberi, kesempatan, un...",terima kasih sudah memberi kesempatan untuk ya...
41,03dc5e28-0e6f-403a-87f1-694e00c29b5d,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,astaga ipusnas... kenapa makin jelek aja sih.....,1,15,2.0.6,2026-01-29 23:28:07,Hallo Pujiana! Kami mohon maaf atas ketidaknya...,2023-10-01 07:16:16,2.0.6,astaga ipusnas kenapa makin jelek aja sih sebe...,astaga ipusnas kenapa makin jelek aja sih sebe...,astaga ipusnas kenapa makin jelek aja sih sebe...,"[astaga, ipusnas, kenapa, makin, jelek, aja, s...","[astaga, ipusnas, kenapa, makin, jelek, aja, s...",astaga ipusnas kenapa makin jelek aja sih sebe...
54,b74d631a-0828-44db-bea5-8d459c8ca039,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,Koleksi bukunya banyak banget! Meski harus nga...,5,2,2.1.0,2026-02-13 03:10:28,Hallo Pine! Kami mohon maaf atas kendala dan k...,2024-05-20 22:44:26,2.1.0,Koleksi bukunya banyak banget Meski harus ngan...,koleksi bukunya banyak banget meski harus ngan...,koleksi bukunya banyak banget meski harus ngan...,"[koleksi, bukunya, banyak, banget, meski, haru...","[koleksi, bukunya, banyak, banget, meski, haru...",koleksi bukunya banyak banget meski harus ngan...